### ISSUE TITLE
Internal Compiler Error during ./jenkins-build.sh

### ISSUE THREAD

**Issue by harrison-seow-seagate** [Seagate/cortx-s3server#787]
Following after successful init (from [issue](https://github.com/Seagate/cortx-s3server/issues/786)), I encountered an error when running `./jenkins-build.sh` (from [guide](https://github.com/Seagate/cortx-s3server/blob/main/docs/CORTX-S3%20Server%20Quick%20Start%20Guide.md#13-code-compilation-and-unit-test)).

**Error Snippet**
```
  ...
  CC       reqh/ut/motr_libmotr_la-io_fop_xc.lo
  CC       reqh/ut/motr_libmotr_la-service_xc.lo
  CCLD     motr/libmotr.la
  CC       motr/motr_libmotr_altogether_la-motr_altogether_user.lo
{standard input}: Assembler messages:
{standard input}:62448: Warning: end of file not at end of a line; newline inserted
{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
gcc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[2]: *** [motr/motr_libmotr_altogether_la-motr_altogether_user.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

```

**Comment by Saumya-Sunder** [comment]
Hey @harrison-seow-seagate , have you installed motr or are you running s3 independently? @nileshgovande we had a similar issue previously, is this not fixed?

**Comment by harrison-seow-seagate** [comment]
Hi @Saumya-Sunder, I'm running s3 independently

**Comment by sachitanands** [comment]
Hi @harrison-seow-seagate s3server uses motr as a submodule with particular commit  has of motr.
Hence if you build s3server then motr will get build automatically.

Please refer the scripts : cortx-s3server/build_thirdparty.sh & cortx-s3server/third_party/build_motr.sh

**Comment by sachitanands** [comment]
Hi @harrison-seow-seagate  regarding gcc compiler error ,
we have seen this error earlier and usually this happens when we ran out of RAM and process gets killed during compilation.
FYI s3server JIRA : https://jts.seagate.com/browse/EOS-14745
**Workaround**  : reboot the vm.
FYI @nileshgovande

**Comment by harrison-seow-seagate** [comment]
I see, I will try again then. Will update if I manage to get it working.
Thanks @sachitanands

**Comment by Saumya-Sunder** [comment]
@sachitanands I think it is better we compile all issues into a troubleshooting guide for S3

**Comment by harrison-seow-seagate** [comment]
Alright, turns out it's RAM issue, I increased RAM from 1GB to 4GB and it worked.
However, after running for a really long time, I encountered another failure on `sh /home/harrison/cortx-s3server/scripts/create_auth_jks_password.sh`

**Error snippet**
```
...
Using /usr/lib/python3.6/site-packages
Searching for six==1.14.0
Best match: six 1.14.0
Adding six 1.14.0 to easy-install.pth file

Using /usr/lib/python3.6/site-packages
Finished processing dependencies for s3iamcli==2.0.0
++ cd -
/home/harrison/cortx-s3server
+ echo 'Stopping any old running s3 services'
Stopping any old running s3 services
+ ./dev-stops3.sh
Waiting for S3 to shutdown...
+ systemctl stop s3authserver
+ cd /home/harrison/cortx-s3server/third_party/motr
+ echo 'Stopping any old running motr services'
Stopping any old running motr services
+ ./m0t1fs/../motr/st/utils/motr_services.sh stop
 MOTR_DIR =/home/harrison/cortx-s3server/third_party/motr/./m0t1fs/..
/home/harrison/cortx-s3server/third_party/motr/./m0t1fs/../m0t1fs/linux_kernel/st
=== pids of services: ===
Shutting down services one by one. mdservice is the last.
Motr services stopped.
Motr services stopped.
+ cd /home/harrison/cortx-s3server
+ rm -rf '/mnt/store/motr/*' '/var/log/motr/*' '/var/log/seagate/motr/*' '/var/log/seagate/s3/*' '/var/log/seagate/auth/server/*' '/var/log/seagate/auth/tools/*' '/var/crash/*'
+ '[' 0 -eq 1 ']'
+ '[' 0 -eq 1 ']'
+ '[' 0 -eq 1 ']'
+ '[' 0 -eq 1 ']'
+ '[' 0 -eq 1 ']'
+ sh /home/harrison/cortx-s3server/scripts/create_auth_jks_password.sh
Generating password for jks keystore used in authserver...
Traceback (most recent call last):
  File "/usr/local/bin/s3cipher", line 4, in <module>
    __import__('pkg_resources').run_script('s3cipher==2.0.0', 's3cipher')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/site-packages/s3cipher-2.0.0-py3.6.egg/EGG-INFO/scripts/s3cipher", line 5, in <module>
  File "/usr/local/lib/python3.6/site-packages/s3cipher-2.0.0-py3.6.egg/s3cipher/cortx_s3_cipher.py", line 26, in <module>
  File "/usr/local/lib/python3.6/site-packages/s3backgrounddelete-2.0.0-py3.6.egg/s3backgrounddelete/cortx_cluster_config.py", line 27, in <module>
    from s3confstore.cortx_s3_confstore import S3CortxConfStore
  File "/usr/local/lib/python3.6/site-packages/s3confstore-2.0.0-py3.6.egg/s3confstore/cortx_s3_confstore.py", line 22, in <module>
ModuleNotFoundError: No module named 'cortx'
ERROR: failed to generate key using py-utils:Cipher utility, exiting.
```

Any ideas?

**Comment by sachitanands** [comment]
Hi @harrison-seow-seagate there are recent changes merged to this on main branch..
Could you please  follow below steps,
1) Rebase your branch with latest main branch code.
2) re-run ansible(init.sh)
3) rebuild s3 using  jenkins-build.sh (this should build s3 and other pks properly)
cc @nileshgovande

**Comment by justinzw** [comment]
Hi @harrison-seow-seagate I just wanted to check-in and see whether you managed to run it again on the main branch and see whether that solved the issue. Thanks again for all your help and contributions!

**Comment by harrison-seow-seagate** [comment]
Hi @justinzw and @sachitanands, thanks for the reply, I got tied up with other stuffs, currently still trying it out.

**Comment by harrison-seow-seagate** [comment]
I believe I'm still facing the same error. I used a new VM and tried the setup today.

**Script**
```
sudo su -

yum install -y git
yum install -y ansible
yum install -y python3
yum install -y epel-release
yum install -y python-pip

pip install pip==20.3.3

systemctl stop firewalld
systemctl disable firewalld
setenforce 0
sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config

# ============= REBOOT VM =============

sudo su -

git clone --recursive https://github.com/Seagate/cortx-s3server.git -b main

cd cortx-s3server
git submodule update --init --recursive && git status

cd ./scripts/env/dev
./init.sh -a

# ============= ENTER GitHub PAT =============
# ============= ENTER Passwords =============
# SSH password, openldap rootDN, openldap IAM admin

cd ../../..
./update-hosts.sh
./jenkins-build.sh
```

**Error snippet**
```
=== pids of services: ===
Shutting down services one by one. mdservice is the last.
Motr services stopped.
Motr services stopped.
+ cd /home/s3-server/cortx-s3server
+ rm -rf '/mnt/store/motr/*' '/var/log/motr/*' '/var/log/seagate/motr/*' '/var/log/seagate/s3/*' '/var/log/seagate/auth/server/*' '/var/log/seagate/auth/tools/*' '/var/crash/*'
+ '[' 0 -eq 1 ']'
+ '[' 0 -eq 1 ']'
+ '[' 0 -eq 1 ']'
+ '[' 0 -eq 1 ']'
+ '[' 0 -eq 1 ']'
+ sh /home/s3-server/cortx-s3server/scripts/create_auth_jks_password.sh
Generating password for jks keystore used in authserver...
Traceback (most recent call last):
  File "/usr/local/bin/s3cipher", line 4, in <module>
    __import__('pkg_resources').run_script('s3cipher==2.0.0', 's3cipher')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/site-packages/s3cipher-2.0.0-py3.6.egg/EGG-INFO/scripts/s3cipher", line 5, in <module>
  File "/usr/local/lib/python3.6/site-packages/s3cipher-2.0.0-py3.6.egg/s3cipher/cortx_s3_cipher.py", line 26, in <module>
  File "/usr/local/lib/python3.6/site-packages/s3backgrounddelete-2.0.0-py3.6.egg/s3backgrounddelete/cortx_cluster_config.py", line 27, in <module>
    from s3confstore.cortx_s3_confstore import S3CortxConfStore
  File "/usr/local/lib/python3.6/site-packages/s3confstore-2.0.0-py3.6.egg/s3confstore/cortx_s3_confstore.py", line 22, in <module>
ModuleNotFoundError: No module named 'cortx'
ERROR: failed to generate key using py-utils:Cipher utility, exiting.
```

**Comment by nileshgovande** [comment]
Can you please try with stable branch @harrison-seow-seagate 
Please note - main branch sometimes is unstable

**Comment by harrison-seow-seagate** [comment]
@nileshgovande , thanks for the suggestion, will try it out soon

**Comment by harrison-seow-seagate** [comment]
Unfortunately, it seems I'm still facing the exact same error.

```
Shutting down services one by one. mdservice is the last.
Motr services stopped.
Motr services stopped.
+ cd /home/s3-server/cortx-s3server
+ rm -rf '/mnt/store/motr/*' '/var/log/motr/*' '/var/log/seagate/motr/*' '/var/log/seagate/s3/*' '/var/log/seagate/auth/server/*' '/var/log/seagate/auth/tools/*' '/var/crash/*'
+ '[' 0 -eq 1 ']'
+ '[' 0 -eq 1 ']'
+ '[' 0 -eq 1 ']'
+ '[' 0 -eq 1 ']'
+ '[' 0 -eq 1 ']'
+ sh /home/s3-server/cortx-s3server/scripts/create_auth_jks_password.sh
Generating password for jks keystore used in authserver...
Traceback (most recent call last):
  File "/usr/local/bin/s3cipher", line 4, in <module>
    __import__('pkg_resources').run_script('s3cipher==2.0.0', 's3cipher')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/site-packages/s3cipher-2.0.0-py3.6.egg/EGG-INFO/scripts/s3cipher", line 5, in <module>
  File "/usr/local/lib/python3.6/site-packages/s3cipher-2.0.0-py3.6.egg/s3cipher/cortx_s3_cipher.py", line 26, in <module>
  File "/usr/local/lib/python3.6/site-packages/s3backgrounddelete-2.0.0-py3.6.egg/s3backgrounddelete/cortx_cluster_config.py", line 27, in <module>
    from s3confstore.cortx_s3_confstore import S3CortxConfStore
  File "/usr/local/lib/python3.6/site-packages/s3confstore-2.0.0-py3.6.egg/s3confstore/cortx_s3_confstore.py", line 22, in <module>
ModuleNotFoundError: No module named 'cortx'
ERROR: failed to generate key using py-utils:Cipher utility, exiting.
```

**Comment by nileshgovande** [comment]
@harrison-seow-seagate Can you pls give the VM details ?
We would like to login and check

**Comment by harrison-seow-seagate** [comment]
Hi @nileshgovande, it's on my local machine, so probably not gonna be easy.

**Comment by harrison-seow-seagate** [comment]
I'm not sure how you could connect to my local machine, but you could let me know what are the things you want me to provide you with, or perhaps setup a time so we could chat instead?

**Comment by harrison-seow-seagate** [comment]
Also, this issue is actually about Internal Compiler Error, caused by insufficient RAM (solved), so I will be closing this and continue on another [issue 895](https://github.com/Seagate/cortx-s3server/issues/895).
