### ISSUE TITLE
./jenkins-build.sh fails with error on s3 tests

### ISSUE THREAD

**Issue by hessio** [Seagate/cortx-s3server#875]
```
s3confstore UT's runs successfully
Executing ST`s over HTTPS
Check S3CMD...OK
Check s3iamcli...OK
Check jclient.jar...OK
Check jcloudclient.jar...OK
Check parallel...OK\Check bc...OK
Check md5sum...OK
Check seagate host entries for system test...OK
Fri Apr 30 14:52:32 UTC 2021: Running backgrounddelete_spec.py
Configuring LDAP
Traceback (most recent call last):
  File "backgrounddelete_spec.py", line 53, in <module>
    before_all()
  File "backgrounddelete_spec.py", line 50, in before_all
    S3PyCliTest('Before_all').before_all()
  File "/root/cortx-s3server/st/clitests/framework.py", line 232, in before_all
    ldap_setup = LdapSetup()
  File "/root/cortx-s3server/st/clitests/ldap_setup.py", line 30, in __init__
    self.ldap_config = yaml.safe_load(f)
  File "/usr/local/lib64/python3.6/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib64/python3.6/site-packages/yaml/__init__.py", line 112, in load
    loader = Loader(stream)
  File "/usr/local/lib64/python3.6/site-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/lib64/python3.6/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/usr/local/lib64/python3.6/site-packages/yaml/reader.py", line 135, in determine_encoding
    self.update(1)
  File "/usr/local/lib64/python3.6/site-packages/yaml/reader.py", line 169, in update
    self.check_printable(data)
  File "/usr/local/lib64/python3.6/site-packages/yaml/reader.py", line 144, in check_printable
    'unicode', "special characters are not allowed")
yaml.reader.ReaderError: unacceptable character #x001b: special characters are not allowed
  in "/root/cortx-s3server/st/clitests/test_data/ldap_config.yaml", position 825
***************
*** ABORTED ***
***************
Error encountered. Exiting ST prematurely...
***************
*** ABORTED ***
***************
Error encountered. Exiting test runs prematurely...
+ echo 'S3 Tests failed.'
S3 Tests failed.
+ S3_TEST_RET_CODE=1
+ sed -i 's/enableFaultInjection=.*$/enableFaultInjection=false/g' /opt/seagate/cortx/auth/resources/authserver.properties
+ systemctl stop s3authserver
+ ./dev-stops3.sh
Waiting for S3 to shutdown...
+ '[' 0 -eq 1 ']'
+ tail -50 /var/log/seagate/s3/s3server.ERROR
tail: cannot open ‘/var/log/seagate/s3/s3server.ERROR’ for reading: No such file or directory
+ echo 'No Errors'
No Errors
+ '[' '!' -z '' ']'
+ cd /root/cortx-s3server/third_party/motr
+ ./m0t1fs/../motr/st/utils/motr_services.sh stop
 MOTR_DIR =/root/cortx-s3server/third_party/motr/./m0t1fs/..
/root/cortx-s3server/third_party/motr/./m0t1fs/../m0t1fs/linux_kernel/st
=== pids of services: 88929 88915 88905 88898 88894 88803 88711 87972 ===
Shutting down services one by one. mdservice is the last.
----- 88929 stopping--------lt-m0d: got signal 1
motr[88929]:  1f00  ERROR  [conf/rconfc.c:1199:rconfc_fail]  rconfc: 0x7fffb2fa8688, state M0_RCS_IDLE failed with -22
----- 88929 stopped --------
----- 88915 stopping--------lt-m0d: got signal 1
motr[88915]:  1040  ERROR  [conf/rconfc.c:1199:rconfc_fail]  rconfc: 0x7ffd345677c8, state M0_RCS_IDLE failed with -22
----- 88915 stopped --------
----- 88905 stopping--------lt-m0d: got signal 1
motr[88905]:  d4f0  ERROR  [conf/rconfc.c:1199:rconfc_fail]  rconfc: 0x7fff265a3c78, state M0_RCS_IDLE failed with -22
----- 88905 stopped --------
----- 88898 stopping--------lt-m0d: got signal 1
motr[88898]:  94a0  ERROR  [conf/rconfc.c:1199:rconfc_fail]  rconfc: 0x7ffef49bfc28, state M0_RCS_IDLE failed with -22
----- 88898 stopped --------
----- 88894 stopping--------lt-m0d: got signal 1
motr[88894]:  8480  ERROR  [conf/rconfc.c:1199:rconfc_fail]  rconfc: 0x7ffd580aec08, state M0_RCS_IDLE failed with -22
----- 88894 stopped --------
----- 88803 stopping--------lt-m0d: got signal 1
----- 88803 stopped --------
----- 88711 stopping--------lt-m0d: got signal 1
motr[88711]:  a860   WARN  [ha/link.c:1513:ha_link_outgoing_fom_tick]  rlk_rc=-110 endpoint=192.168.23.180@tcp:12345:33:800
motr[88711]:  a860   WARN  [ha/link.c:1513:ha_link_outgoing_fom_tick]  rlk_rc=-110 endpoint=192.168.23.180@tcp:12345:33:900
----- 88711 stopped --------
----- 87972 stopping--------lt-m0d: got signal 1
----- 87972 stopped --------
m0tr                13990510  0
galois                 22944  1 m0tr
lnet                  590949  3 m0tr,ksocklnd
Motr services stopped.
Motr services stopped.
+ cd /root/cortx-s3server
+ '[' 0 -eq 1 ']'
+ exit 1
```

**Comment by hessio** [comment]
Spelling mistake when entering password for openldap rootDN for `./init.sh -a` command caused this issue, and it has since been resolved.
