### ISSUE TITLE
./jenkins-build.sh fails

### ISSUE THREAD

**Issue by hessio** [Seagate/cortx-s3server#881]
```
Test case [Create account s3-background-delete-svc] - Script result: python36 /root/cortx-s3server/st/clitests/../../scripts/ldap/create_account_using_cipher.py CreateBGDeleteAccount --ldapuser sgiamadmin --ldappasswd ldapadmin
  return code: 1
-- stderr: --------------------
Traceback (most recent call last):
  File "/root/cortx-s3server/st/clitests/../../scripts/ldap/create_account_using_cipher.py", line 24, in <module>
    from ldapaccountaction import LdapAccountAction
  File "/root/cortx-s3server/scripts/ldap/ldapaccountaction.py", line 21, in <module>
    import ldap
ModuleNotFoundError: No module named 'ldap'
Traceback (most recent call last):
  File "backgrounddelete_spec.py", line 133, in <module>
    result = AuthTest(test_msg).create_cipher_account(**account_args).execute_test()
  File "/root/cortx-s3server/st/clitests/framework.py", line 142, in execute_test
    self.run()
  File "/root/cortx-s3server/st/clitests/auth.py", line 34, in run
    super(AuthTest, self).run(cmd_args)
  File "/root/cortx-s3server/st/clitests/framework.py", line 104, in run
    self.status = self.env.run(self.command, expect_error=expect_error_value, stdin=stdin_param, expect_stderr=expect_stderr_value)
  File "/usr/lib/python3.6/site-packages/scripttest.py", line 273, in run
    result.assert_no_error(quiet)
  File "/usr/lib/python3.6/site-packages/scripttest.py", line 427, in assert_no_error
    "Script returned code: %s" % self.returncode)
AssertionError: Script returned code: 1
***************
*** ABORTED ***
***************
Error encountered. Exiting ST prematurely...
***************
*** ABORTED ***
***************
Error encountered. Exiting test runs prematurely...
+ echo 'S3 Tests failed.'
S3 Tests failed.
```

**Comment by sachitanands** [comment]
Hi @hessio could you please confirm if you have right package installed on your machine ..
[root@ssc-vm-4060 cortx-s3server]# pip3 list installed | grep ldap
python-ldap            3.3.1
[root@ssc-vm-4060 cortx-s3server]#
also please try once with fresh vm if possible.
cc @nileshgovande

**Comment by nileshgovande** [comment]
@hessio is it still a valid issue? please close if you do not see it on latest steps.

**Comment by hessio** [comment]
Guide now fails before this, so I cannot get to this step.
