### ISSUE TITLE
./jenkins-build.sh ERROR: failed to generate key using py-utils

### ISSUE THREAD

**Issue by harrison-seow-seagate** [Seagate/cortx-s3server#895]
Continued from [Issue 787](https://github.com/Seagate/cortx-s3server/issues/787), when running jenkins-build.sh, script failed to generate key using py-utils

**Steps to reproduce**
```
sudo su -

yum install -y git
yum install -y ansible
yum install -y python3
yum install -y epel-release
yum install -y python-pip

pip install pip==20.3.3

systemctl stop firewalld
systemctl disable firewalld
setenforce 0
sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config

# ============= REBOOT VM =============

sudo su -

git clone --recursive https://github.com/Seagate/cortx-s3server.git -b main

cd cortx-s3server
git submodule update --init --recursive && git status

cd ./scripts/env/dev
./init.sh -a

# ============= ENTER GitHub PAT =============
# ============= ENTER Passwords =============
# SSH password, openldap rootDN, openldap IAM admin

cd ../../..
./update-hosts.sh
./jenkins-build.sh
```

**Error snippet**
```
Shutting down services one by one. mdservice is the last.
Motr services stopped.
Motr services stopped.
+ cd /home/s3-server/cortx-s3server
+ rm -rf '/mnt/store/motr/*' '/var/log/motr/*' '/var/log/seagate/motr/*' '/var/log/seagate/s3/*' '/var/log/seagate/auth/server/*' '/var/log/seagate/auth/tools/*' '/var/crash/*'
+ '[' 0 -eq 1 ']'
+ '[' 0 -eq 1 ']'
+ '[' 0 -eq 1 ']'
+ '[' 0 -eq 1 ']'
+ '[' 0 -eq 1 ']'
+ sh /home/s3-server/cortx-s3server/scripts/create_auth_jks_password.sh
Generating password for jks keystore used in authserver...
Traceback (most recent call last):
  File "/usr/local/bin/s3cipher", line 4, in <module>
    __import__('pkg_resources').run_script('s3cipher==2.0.0', 's3cipher')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/site-packages/s3cipher-2.0.0-py3.6.egg/EGG-INFO/scripts/s3cipher", line 5, in <module>
  File "/usr/local/lib/python3.6/site-packages/s3cipher-2.0.0-py3.6.egg/s3cipher/cortx_s3_cipher.py", line 26, in <module>
  File "/usr/local/lib/python3.6/site-packages/s3backgrounddelete-2.0.0-py3.6.egg/s3backgrounddelete/cortx_cluster_config.py", line 27, in <module>
    from s3confstore.cortx_s3_confstore import S3CortxConfStore
  File "/usr/local/lib/python3.6/site-packages/s3confstore-2.0.0-py3.6.egg/s3confstore/cortx_s3_confstore.py", line 22, in <module>
ModuleNotFoundError: No module named 'cortx'
ERROR: failed to generate key using py-utils:Cipher utility, exiting.
```

**Comment by nileshgovande** [comment]
@harrison-seow-seagate - Can we get access to system ?

Did you follow the latest steps in QuickStart Guide?
Do you have py-utils installed on your system?

**Comment by harrison-seow-seagate** [comment]
For you to access my local VM, I think I will need to setup port forwarding and most importantly be online? In that case perhaps a chat would be faster.

I can't believe I missed the Python utilities installation, I didn't notice there's an update for Kafka installations as well. Might as well restart the whole VM setup, thanks.

**Comment by nileshgovande** [comment]
No response for 1 month. Closing. Please retry with the latest s3 and reopen as applicable.
