### ISSUE TITLE
./jenkins-build.sh failure

### ISSUE THREAD

**Issue by hessio** [Seagate/cortx-s3server#904]
When I run the command I get this error:

```
[root@cortx-deploy cortx-s3server]# ./jenkins-build.sh
Using HTTPS for system tests
++ pwd
+ S3_BUILD_DIR=/root/cortx-s3server
+ ANSIBLE_DIR=/root/cortx-s3server/scripts/env/dev
+ USE_SUDO=
+ [[ 0 -ne 0 ]]
+ [[ 0 -eq 1 ]]
+ source /root/.s3_ldap_cred_cache.conf
++ ldap_root_pwd=seagate
++ ldap_admin_pwd=ldapadmin
+ '[' '' '!=' '' ']'
+ '[' '' '!=' '' ']'
+ '[' '' '!=' '' ']'
+ export PATH=/opt/seagate/cortx/s3/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
+ PATH=/opt/seagate/cortx/s3/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
+ echo /opt/seagate/cortx/s3/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
/opt/seagate/cortx/s3/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
+ ulimit -c unlimited
+ rpm -q haproxy
haproxy-1.8.14-1.el7.x86_64
+ systemctl status haproxy
● haproxy.service - HAProxy Load Balancer
   Loaded: loaded (/usr/lib/systemd/system/haproxy.service; disabled; vendor preset: disabled)
   Active: active (running) since Thu 2021-05-13 13:02:54 EDT; 36min ago
  Process: 114632 ExecStartPre=/usr/sbin/haproxy -f $CONFIG -c -q (code=exited, status=0/SUCCESS)
 Main PID: 114634 (haproxy)
   CGroup: /system.slice/haproxy.service
           ├─114634 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid
           └─114637 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid

May 13 13:02:54 cortx-deploy systemd[1]: Starting HAProxy Load Balancer...
May 13 13:02:54 cortx-deploy systemd[1]: Started HAProxy Load Balancer.
+ cd /root/cortx-s3server
+ '[' 0 -eq 1 ']'
+ is_authsrv_running=1
+ systemctl is-active s3authserver
+ is_authsrv_running=0
+ [[ 0 -eq 1 ]]
+ THIRD_PARTY=/root/cortx-s3server/third_party
+ MOTR_SRC=/root/cortx-s3server/third_party/motr
+ BUILD_CACHE_DIR=/root/.seagate_src_cache
+ cd /root/cortx-s3server/third_party/motr
++ git rev-parse HEAD
+ current_motr_rev=1725ba73a4f2b1c8a64c8dab0f2cf8bc8e84c1e2
+ cd /root/cortx-s3server
++ cat /root/.seagate_src_cache/cached_motr.git.rev
+ cached_motr_rev=1725ba73a4f2b1c8a64c8dab0f2cf8bc8e84c1e2
+ '[' 1725ba73a4f2b1c8a64c8dab0f2cf8bc8e84c1e2 '!=' 1725ba73a4f2b1c8a64c8dab0f2cf8bc8e84c1e2 ']'
+ valgrind_flag=
+ '[' '' '!=' '' ']'
+ '[' 0 -eq 0 ']'
+ extra_opts=
+ '[' 0 -ne 0 ']'
+ '[' 0 -ne 0 ']'
+ ./rebuildall.sh --no-motr-rpm --use-build-cache
+++ pwd
++ S3_SRC_DIR=/root/cortx-s3server
++ BUILD_CACHE_DIR=/root/.seagate_src_cache
++ motr_include_path='"-I'
++ declare MOTR_LINK_LIB_
++ '[' 0 -eq 1 ']'
++ '[' 0 -eq 0 ']'
++ ./checkcodeformat.sh
Traceback (most recent call last):
  File "/usr/bin/git-clang-format", line 27, in <module>
    import argparse
ImportError: No module named argparse
[ERROR:Code formatting]
One or more modified files do not comply with clang-format.
Run below command to see required changes:
        'git clang-format --style=Google --extensions=c,cc,h,java --diff --commit HEAD~1'


Code formatting check...Failed
[root@cortx-deploy cortx-s3server]# git clang-format --style=Google --extensions=c,cc,h,java --diff --commit HEAD~1
Traceback (most recent call last):
  File "/usr/bin/git-clang-format", line 27, in <module>
    import argparse
ImportError: No module named argparse
[root@cortx-deploy cortx-s3server]#
```

**Comment by nileshgovande** [comment]
Try running 'yum install python-argparse'

**Comment by hessio** [comment]
Ok I tried this:
