### ISSUE TITLE
EOS-21263 - init.sh fails

### ISSUE THREAD

**Issue by hessio** [Seagate/cortx-s3server#908]
```
Traceback (most recent call last):
  File "/usr/local/bin/githubrelease", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1134, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1059, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1665, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1665, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1401, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 767, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/github_release.py", line 840, in _cli_asset_download
    gh_asset_download(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/github_release.py", line 883, in gh_asset_download
    _download_file(repo_name, asset)
  File "/usr/local/lib/python3.6/site-packages/github_release.py", line 859, in _download_file
    label=asset['name'], length=asset['size']) as reporter:
  File "/usr/local/lib/python3.6/site-packages/click/_termui_impl.py", line 98, in __enter__
    self.render_progress()
  File "/usr/local/lib/python3.6/site-packages/click/_termui_impl.py", line 242, in render_progress
    line = self.format_progress_line()
  File "/usr/local/lib/python3.6/site-packages/click/_termui_impl.py", line 193, in format_progress_line
    info_bits.append(self.format_pos())
  File "/usr/local/lib/python3.6/site-packages/github_release.py", line 141, in formatPos
    if _self.length_known:
AttributeError: 'ProgressBar' object has no attribute 'length_known'
[root@cortx-deploy dev]#
```

**Comment by nileshgovande** [comment]
At which step was this error observed in QSG ?
What is the environment (ssc-vm ? vmware ?)
Can we share details ?

**Comment by hessio** [comment]
I used the main branch, I guess I should have used `stable` branch?

**Comment by hessio** [comment]
@justinzw can you see if you can reproduce this issue for @nileshgovande in the interactive session?

**Comment by nileshgovande** [comment]
This seems to be an issue with GitHubRelease not able to download from https://github.com/Seagate/cortx/releases/tag/build-dependencies


TAG_NAME="build-dependencies"
githubrelease --github-token "Your_token" asset seagate/cortx download "${TAG_NAME}"

@shailesh-vaidya  and @mukul-seagate11 - Please help

**Comment by justinzw** [comment]
I have run into this issue on an AWS and VMware Workstation.  I will send details on how to access the AWS machine

**Comment by shailesh-vaidya** [comment]
Manual download is working fine. 
```
[root@91c449829bd8 aws-test]# GITHUB_TOKEN=<GITHUB TOKEN>
[root@91c449829bd8 aws-test]# githubrelease --github-token $GITHUB_TOKEN asset seagate/cortx download build-dependencies
release build-dependencies: downloading bazel-0.13.0-1.el7.x86_64.rpm
  [####################################]  98.08M/98.08M  100%  bazel-0.13.0-1.el7.x86_64.rpm
release build-dependencies: downloading compat-lua-libs-5.1.5-3.el7.x86_64.rpm
release build-dependencies: downloading consul-1.7.8-1.x86_64.rpm
  [####################################]  30.06M/30.06M  100%  consul-1.7.8-1.x86_64.rpm
release build-dependencies: downloading git-clang-format-6.0-1.el7.x86_64.rpm
release build-dependencies: downloading gtest-1.10.0-1.el7.x86_64.rpm
release build-dependencies: downloading gtest-devel-1.10.0-1.el7.x86_64.rpm
release build-dependencies: downloading haproxy-1.8.14-1.el7.x86_64.rpm
release build-dependencies: downloading haproxy-statsd-1.0-1.x86_64.rpm
release build-dependencies: downloading isa-l-2.30.0-1.el7.x86_64.rpm
release build-dependencies: downloading libevhtp-1.2.18-2.el7.x86_64.rpm
release build-dependencies: downloading libevhtp-devel-1.2.18-2.el7.x86_64.rpm
release build-dependencies: downloading libntirpc-1.8.1-0.1.el7.x86_64.rpm
release build-dependencies: downloading libntirpc-devel-1.8.1-0.1.el7.x86_64.rpm
release build-dependencies: downloading log4cxx_cortx-0.10.0-1.x86_64.rpm
release build-dependencies: downloading log4cxx_cortx-devel-0.10.0-1.x86_64.rpm
release build-dependencies: downloading lua-5.3.0-2.el7.x86_64.rpm
release build-dependencies: downloading nfs-ganesha-2.8.4-0.1.el7.x86_64.rpm
release build-dependencies: downloading nfs-ganesha-vfs-2.8.4-0.1.el7.x86_64.rpm
release build-dependencies: downloading ossperf-3.0-1.x86_64.rpm
release build-dependencies: downloading python-jmespath-0.9.0-1.el7.noarch.rpm
release build-dependencies: downloading python-wheel-0.24.0-2.el7.noarch.rpm
release build-dependencies: downloading python2-botocore-1.6.0-1.el7.noarch.rpm
release build-dependencies: downloading python2-jmespath-0.9.0-1.el7.noarch.rpm
release build-dependencies: downloading python2-s3transfer-0.1.10-1.el7.noarch.rpm
release build-dependencies: downloading python36-boto3-1.4.6-1.el7.noarch.rpm
release build-dependencies: downloading python36-botocore-1.6.0-1.el7.noarch.rpm
release build-dependencies: downloading python36-cortx-prvsnr-0.36.0-1.0.0.x86_64.rpm
release build-dependencies: downloading python36-jmespath-0.9.0-1.el7.noarch.rpm
release build-dependencies: downloading python36-s3transfer-0.1.10-1.el7.noarch.rpm
release build-dependencies: downloading python36-wheel-0.24.0-2.el7.noarch.rpm
release build-dependencies: downloading python36-xmltodict-0.9.0-1.el7.noarch.rpm
release build-dependencies: downloading s3cmd-1.6.1-1.el7.noarch.rpm
release build-dependencies: downloading systemd-python36-1.0.0-523_git7908548.el7.x86_64.rpm
release build-dependencies: downloading systemd-python36-debuginfo-1.0.0-523_git7908548.el7.x86_64.rpm
[root@91c449829bd8 aws-test]# 
```

**Comment by shailesh-vaidya** [comment]
Issue is caused due to one of the dependency package named `click` of `githubrelease`. In recent `click==8.0.1` release they have removed `length_known` attribute. 
Refer - https://www.gitmemory.com/issue/girder/girder/3357/850392017  and https://pypi.org/project/click/8.0.1/

As a workaround we can use below steps for installing githubrelease package - 
```
export LANG=en_US.UTF-8 && export LC_ALL=en_US.UTF-8
pip3 install click==7.1.2 && pip3 install githubrelease
```
Validated this on fresh system. Please test and let me know if any issues. 

For future prospective may be we should go away from `githubrelease` and use some other option. There is standard [GitHub CLI ](https://github.com/cli/cli) . However I found that it does not support public release download without authentication as of now.  Refer - https://github.com/cli/cli/discussions/3820

**Comment by nileshgovande** [comment]
Issue fixed against https://github.com/Seagate/cortx-s3server/pull/980/files
